@startuml ADeus
title ADeus
autonumber

Actor user
Participant "device/raspi" as device
Participant "chatbot/phone" as chatbot
box "supabase" #lightBlue
  Participant supabase
box
box "openai" #lightGreen
  Participant whisper
  Participant embeddings
  Participant GPT
end box

== build data ==
user -> device : speech
device -> supabase : audio
supabase -> whisper : audio
whisper -> supabase : text
supabase -> embeddings : text
embeddings -> supabase : embeddings
supabase -> supabase : store to db

== total recall ==
user -> chatbot : text(conversation)
chatbot -> supabase : text(conversation)
supabase -> embeddings : text(conversation)
embeddings -> supabase : embeddings
supabase -> supabase : db query(embeddings match)
supabase -> GPT : prompt, text(conversation), matched db embeddings
GPT -> supabase : response
supabase -> chatbot : response
chatbot -> user : response

@enduml